### ISSUE TITLE
TinTimer Shortcut Keys

### ISSUE THREAD

**Issue by vlykarye** [kaneorotar/Mabinogi_INI_Script#1]
Webpage says     默认快捷键 （可在TinTimer.USER.ini内修改）   but does not show how. Could you add some information on it? Thank you!

**Comment by kaneorotar** [comment]
> 
> 
> Webpage says 默认快捷键 （可在TinTimer.USER.ini内修改） but does not show how. Could you add some information on it? Thank you!

Sorry, that's feature will be ready in the next release.
